config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :likes
    end
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :boards, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :video, VideoUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :board_tags, dependent: :destroy
  has_many :tags, through: :board_tags

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
  validates :video, :presence => true

  def save_tag(tag_list)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - tag_list
    new_tags = tag_list - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      board_tag = Tag.find_or_create_by(name: new_name)
      tags << board_tag
    end
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::BaseController
  before_action :set_board, only: %i[edit update show destroy]
  
  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end
  
  def edit; end
  
  def update
    if @board.update(board_params)
      redirect_to admin_board_path(@board), success: 'クリップを更新しました。'
    else
      flash.now['danger'] = 'クリップの更新に失敗しました。'
      render :edit
    end
  end
  
  def show; end
  
  def destroy
    @board.destroy!
    redirect_to admin_boards_path, success: 'クリップを削除しました。'
  end
  
  private
  
  def set_board
    @board = Board.find(params[:id])
  end
  
    def board_params
      params.require(:board).permit(:title, :body, :video)
    end
  end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :check_guest, only: [:create, :update, :destroy]

  def index
    @tag = Tag.find(params[:tag_id]) if params[:tag_id].present?
    @boards = @tag.boards.includes(:user).order(created_at: :desc).page(params[:page]).per(10) if @tag
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    tag_list = params[:board][:tag_names].split(/,|、/)
    if @board.save
      @board.save_tag(tag_list)
      redirect_to boards_path, success: '新規作成しました'
    else
      flash.now['danger'] = '新規作成に失敗しました'
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @board = current_user.boards.find(params[:id])
    @tag_list = @board.tags.pluck(:name).join(',')
  end

  def update
    @board = Board.find(params[:id])
    tag_list = params[:board][:tag_names].split(/,|、/)
    if @board.update(board_params)
      @board.save_tag(tag_list)
      redirect_to @board, success: '投稿を更新しました'
    else
      flash.now['danger'] = '投稿を更新できませんでした'
      render :edit
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    redirect_to boards_path, success: '投稿を削除しました'
  end

  def likes
    @q = current_user.like_boards.ransack(params[:q])
    @like_boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def board_params
    params.require(:board).permit(:title, :body, :video, :name)
  end

  def check_guest
    return unless current_user.email == 'guest@example.com'
    redirect_to boards_path, warning: 'ゲストユーザーはこのアクションを実行できません。'
  end
end

app/views/admin/boards/_board.html.erb
<tr>
  <td>
    <%= board.id %>
  </td>
  <td>
    <%= link_to board.title, admin_board_path(board) %>
  </td>
  <td>
    <%= board.user.decorate.nickname %>
  </td>
  <td>
    <%= l board.created_at, format: :long %>
  </td>
  <td>
    <%= link_to '詳細', admin_board_path(board), class: 'btn btn-info' %>
    <%= link_to '編集', edit_admin_board_path(board), class: 'btn btn-success' %>
    <%= link_to '削除', admin_board_path(board), method: :delete, data: { confirm: '削除しますか？' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/boards/_search_form.html.erb
<%= search_form_for @q, url: admin_boards_path do |f| %>
  <div class="row">
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto">
        <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: '検索ワード' %>
      </div>
      <div class="col-auto">
        <%= f.date_field :created_at_gteq, class: 'form-control' %>
        <span>〜</span>
        <%= f.date_field :created_at_lteq_end_of_day, class: 'form-control' %>
      </div>
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/boards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= '編集' %></h1>
      <%= form_with model: @board, url: admin_board_path(@board), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 10 %>
        </div>
        <div class="field">
          <%= f.label :video %><br>
          <%= f.file_field :video, :accept => 'video/*' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/boards/index.html.erb
<div class="container mb-5 pt-2">
  <h1><%= 'クリップ一覧' %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Board.human_attribute_name(:id) %></th>
          <th scope="col"><%= Board.human_attribute_name(:title) %></th>
          <th scope="col"><%= Board.human_attribute_name(:user) %></th>
          <th scope="col"><%= Board.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @boards %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @boards %>
    </div>
  </div>
</div>

app/views/admin/boards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= 'クリップ詳細' %></h1>
      <div class="text-right mb-3">
        <%= link_to '編集', edit_admin_board_path(@board), class: 'btn btn-success' %>
        <%= link_to '削除', admin_board_path(@board), method: :delete, data: { confirm: '削除しますか？' }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:id) %></th>
          <td><%= @board.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:title) %></th>
          <td><%= @board.title %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:user) %></th>
          <td><%= @board.user.decorate.nickname %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:body) %></th>
          <td><%= @board.body %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:created_at) %></th>
          <td><%= l @board.created_at, format: :long %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:video) %></th>
          <td><%= video_tag @board.video.url, autoplay: true, muted: false, class: 'video-player', controls: true %></td>
        </tr>
      </table>
    </div>
  </div>
</div>